"""init

Revision ID: a8ea7187ceb0
Revises: f93a982301a5
Create Date: 2020-07-25 17:21:52.569661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ea7187ceb0'
down_revision = 'f93a982301a5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_login'), 'users', ['login'])
    op.create_index('user_login', 'users', ['login'], unique=True, mysql_length=255)
    op.drop_index('my_index', table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'value')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('my_index', 'users', ['name'], unique=True)
    op.drop_index('user_login', table_name='users')
    op.drop_constraint(op.f('uq_users_login'), 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
