"""init

Revision ID: 780f2182e674
Revises: 
Create Date: 2020-07-26 16:32:25.691202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780f2182e674'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_index('user_login', 'users', ['login'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_login', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
